services:
  client:
    build:
      context: ./apps/lost-and-found-client/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./apps/lost-and-found-client:/app:delegated
      - /app/node_modules
    depends_on:
      - server
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_ADDRESS}

  server:
    build: ./apps/lost-and-found-server/
    ports:
      - "3000:3000"
    volumes:
      - ./apps/lost-and-found-server:/app:delegated
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet"]

volumes:
  mongo-data:
